version: "3"
services:
  suporte-quarkus-backend:
    container_name: exemplo-quarkus
    image: exemplo-quarkus:latest
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
      args:
        - JAR_FILE=target/exemplo-quarkus-1.0.0-SNAPSHOT.jar
        - CONTEXT=exemplo-quarkus
    ports:
      - 8088:8080
    env_file:
      - .env
